### ISSUE TITLE
no deauthentication

### ISSUE THREAD

**Issue by karlandy** [RandDruid/esp8266-deauth#5]
set channel = 1
Serial Output looks fine:
DeAuth to ---->CLIENT: eca86b29a101 works with: [NeighborAP1]     33330000000c          6    -94
DeAuth to ---->CLIENT: 789f700f7636 works with: [NeighborAP2]     333300000016          8    -91
DeAuth to ---->CLIENT: 3ca9f4945c2c works with: [NeighborAP3]     333300010002         11    -98
DeAuth to ---->CLIENT: 025ba88e8207 works with: [NeighborAP4]     ffffffffffff         11    -86
DeAuth to ---->CLIENT: 00223f8e713b works with: [MyAP]     XXXXXmyMACXX          1    -67
DeAuth to ---->CLIENT: eca86b29a101 works with: [NeighborAP1]     33330000000c          6    -94
DeAuth to ---->CLIENT: 789f700f7636 works with: [NeighborAP2]     333300000016          8    -91
DeAuth to ---->CLIENT: 3ca9f4945c2c works with: [NeighborAP3]     333300010002         11    -98

what should 00223f8e713b be?
I also see no deauth packets in wireshark
plz help!

**Comment by RandDruid** [comment]
This is MAC address of client.
I think you have issues with wrong SDK version.
